---
- name: reload consul
  become: yes
  become_user: root
  command: /usr/local/bin/consul reload -http-addr=127.0.0.1:{{ consul_http_port | default(8500) }}
  when: not consul_create_image

- name: restart consul
  service:
    name: consul
    state: restarted
  when: consul_upgrade_if_older_version

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  when: not consul_create_image
